name: run hippo

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.x
    - name: restore cache
      run: |
        RUN_ID=$(gh run list --workflow cron.yml --branch main --status completed --limit 1 --json databaseId --jq '.[0].databaseId')
        if [ -n "$RUN_ID" ]; then
          gh run download "$RUN_ID" --name cache
        fi
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
    - name: yarn install
      run: yarn install --immutable
    - name: yarn start
      run: yarn start
      env:
        POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        CC_USERS: ${{ secrets.CC_USERS }}
    - name: persist cache
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # tag: v7.0.0
      with:
        name: cache
        path: .cache
        include-hidden-files: true
